id: P009341
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:34:16.621550
source_metadata:
  id: bdr:W1KG14720
  title: ས་སྐྱ་བཀའ་འབུམ་ལས་ལེ་ཚན་སྣ་ཚོགས། ༼ས་ངོར་པར་མ།༽
  author: ''
  volumes:
    5e2a09ea27804774b839f31bf7540b15:
      image_group_id: I1KG22404
      title: ''
      volume_number: 1
      total_pages: 466
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
